#!/bin/bash
set -e

# ==============================================================================
# Omarchy-Style Ubuntu Setup Script
# Replicates the Omarchy folder structure and toolset for Ubuntu/Debian.
# ==============================================================================

USER_HOME=$(eval echo ~${SUDO_USER:-$USER})
CONFIG_DIR="$USER_HOME/.config"
OMARCHY_DIR="$USER_HOME/.local/share/omarchy"
THEMES_DIR="$OMARCHY_DIR/themes"
BIN_DIR="$USER_HOME/.local/bin"

echo ">> Updating system..."
sudo apt update && sudo apt upgrade -y

echo ">> Installing Core Dependencies..."
# Hyprland is in universe for 24.10+, for 24.04 check if backports or PPA needed.
# Assuming 24.10+ or PPA enabled for Hyprland.
# Common tools: Kitty (terminal), Neovim, Tmux, Waybar, Rofi (launcher),
# SwWW (wallpaper), Dunst (notifications), Git, Curl.
sudo apt install -y \
    build-essential git curl wget \
    hyprland waybar rofi-wayland \
    kitty neovim tmux \
    dunst libnotify-bin \
    xdg-desktop-portal-hyprland \
    qt5-style-plugins qt6ct \
    ttf-font-awesome fonts-noto-color-emoji

# Note: swww (wallpaper) might need building or manual install if not in repos
# For simplicity, we use hyprpaper if available, else skip wallpaper daemon.
if apt-cache show hyprpaper >/dev/null 2>&1; then
    sudo apt install -y hyprpaper
else
    echo ">> Hyprpaper not in repo, skipping wallpaper daemon install."
fi

echo ">> Creating Omarchy Directory Structure..."
mkdir -p "$CONFIG_DIR/hypr"
mkdir -p "$THEMES_DIR/default"
mkdir -p "$BIN_DIR"

# ==============================================================================
# 1. Layered Config Approach
# ==============================================================================
# Omarchy splits configs into 'system' (read-only) and 'user' (overrides).
# We simulate this by creating a base config that sources a theme config.

echo ">> Generating Hyprland Configs..."

# The Base Hyprland Config
cat <<EOF > "$CONFIG_DIR/hypr/hyprland.conf"
# [Omarchy-Ubuntu] Base Configuration
# Do not edit this file directly for personalization.
# Use ~/.config/hypr/user.conf for overrides.

# 1. Source the Theme (Symlink managed)
source = ~/.config/hypr/theme.conf

# 2. Source User Overrides
source = ~/.config/hypr/user.conf

# Core Keybindings (Omarchy Style: Super+...)
\$mainMod = SUPER

bind = \$mainMod, Q, exec, kitty
bind = \$mainMod, C, killactive,
bind = \$mainMod, M, exit,
bind = \$mainMod, E, exec, kitty -e tmux
bind = \$mainMod, V, togglefloating,
bind = \$mainMod, R, exec, rofi -show drun
bind = \$mainMod, P, pseudo, # dwindle
bind = \$mainMod, J, togglesplit, # dwindle

# Focus with Super + HJKL (Vim style)
bind = \$mainMod, h, movefocus, l
bind = \$mainMod, l, movefocus, r
bind = \$mainMod, k, movefocus, u
bind = \$mainMod, j, movefocus, d

# Switch workspaces 1-10
bind = \$mainMod, 1, workspace, 1
bind = \$mainMod, 2, workspace, 2
bind = \$mainMod, 3, workspace, 3
bind = \$mainMod, 4, workspace, 4
bind = \$mainMod, 5, workspace, 5
bind = \$mainMod, 6, workspace, 6
bind = \$mainMod, 7, workspace, 7
bind = \$mainMod, 8, workspace, 8
bind = \$mainMod, 9, workspace, 9
bind = \$mainMod, 0, workspace, 10

# Startup
exec-once = waybar
exec-once = dunst
EOF

# Create a Dummy User Config
touch "$CONFIG_DIR/hypr/user.conf"

# ==============================================================================
# 2. Theme Management (Symlinks)
# ==============================================================================

echo ">> Creating Default Theme..."

# Create Default Theme File
cat <<EOF > "$THEMES_DIR/default/hypr.conf"
# Default Theme Settings
general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)
    layout = dwindle
}

decoration {
    rounding = 10
    blur {
        enabled = true
        size = 3
        passes = 1
    }
}
EOF

# Script to switch themes (Omarchy glue)
cat <<EOF > "$BIN_DIR/omarchy-theme"
#!/bin/bash
THEME=\$1
if [ -z "\$THEME" ]; then
    echo "Usage: omarchy-theme <theme-name>"
    ls $THEMES_DIR
    exit 1
fi

if [ -d "$THEMES_DIR/\$THEME" ]; then
    ln -sf "$THEMES_DIR/\$THEME/hypr.conf" "$CONFIG_DIR/hypr/theme.conf"
    echo "Switched to \$THEME"
    # Reload hyprland
    hyprctl reload
else
    echo "Theme \$THEME not found."
fi
EOF
chmod +x "$BIN_DIR/omarchy-theme"

# Apply Default Theme
"$BIN_DIR/omarchy-theme" default

# ==============================================================================
# 3. Shell Integration
# ==============================================================================

echo ">> Setting up Shell Environment..."
# Add local bin to PATH in .bashrc if not present
if ! grep -q "$BIN_DIR" "$USER_HOME/.bashrc"; then
    echo 'export PATH="$HOME/.local/bin:$PATH"' >> "$USER_HOME/.bashrc"
fi

# ==============================================================================
# 4. Final Instructions
# ==============================================================================

echo "--------------------------------------------------------"
echo "Omarchy-Ubuntu setup complete!"
echo "1. Type 'Hyprland' to start the session."
echo "2. Use 'Super+Q' to open Kitty."
echo "3. Use 'Super+R' to open Launcher."
echo "4. Customize overrides in ~/.config/hypr/user.conf"
echo "--------------------------------------------------------"

